name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.9
        bundler: '2.5.22'
        bundler-cache: false
    
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install
    
    - name: Validate podspec
      run: |
        PODSPEC=$(ls *.podspec | head -n 1)
        echo "验证 podspec: $PODSPEC"
        bundle exec pod spec lint $PODSPEC --allow-warnings
